### ISSUE TITLE
How to send customized content by providing a CVPixelBufferRef

### ISSUE THREAD

**Issue by omarojo** [z37soft/INetSyphon_iOS_SDK#1]
First of all, congratulations, your projects are amazing and really cool and useful.

I was trying to understand the code on the SampleTCPServer to send video data to a receptor. 
But honestly I couldnt understand what is going on or what is the sequence. I noticed a **_m_PixelBuffer**_ variable, but I dont know where do you populate that with the camera feed or anything else. 

I have a program that generates a **CVPixelBufferRef** on every frame, and I was wondering how can I provide this CVPixelBufferRef to your library so it streams those video frames through Syphon.

any comments are heavily appreciated  :smile:

**Comment by z37soft** [comment]
Sorry for my messy source code.
-(void)SetSendImage:(CVImageBufferRef)buffer FlipHorizontal:(BOOL)fh FlipVertical:(BOOL)fv;

I think this method is good for you.
Instead of this method;
    [m_TCPSyphonSDK SetSendData:m_PixelBuffer Width:m_TargetCanvasSize.width Height:m_TargetCanvasSize.height];

Could you check a TL_INetTCPSyphonSDK.h?

//-=-= SERVER SECTION -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//Control server
-(void)StartServer:(NSString*)appname;
-(void)StopServer;

-(void)SetSendData:(NSData_)buffer Width:(int)w Height:(int)h;
*_-(void)SetSendImage:(CVImageBufferRef)buffer FlipHorizontal:(BOOL)fh FlipVertical:(BOOL)fv;**

//set parameters
//Default encode type: TCPUDPSyphon::EncodeType_TURBOJPEG
-(void)SetEncodeType:(TCPUDPSyphonEncodeType)encodetype;
//Default encode quality: 0.5 ( bad:0.0, good:1.0 )
-(void)SetEncodeQuality:(float)quality;

//get information
-(NSDictionary_)GetSyphonServerInformation;
-(NSArray_)GetTCPSyphonClientInformation;
-(unsigned int)GetSendingDataSize;
//-=-= SERVER SECTION -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by omarojo** [comment]
Thanks man... it was actually easier to use than what I was thinking, I guess I got confused with all the OpenGL code you have in your sample. thank you :+1:

**Comment by z37soft** [comment]
Yes. My OpenGL code is a bit messy code. 😁
